"use client";

import { useActionState, useState } from "react";
import { placeOrderAction } from "./actions";

type CheckoutFormProps = {
  // Pre-fill only, from the certified Core customer session (see
  // checkout/page.tsx) — undefined for Guest, who sees the fields empty
  // exactly as before. Rendered as defaultValue (uncontrolled), so the user
  // can edit freely and the value actually submitted is whatever is in the
  // input at submit time, never re-imposed from the session.
  initialCustomerName?: string;
  initialCustomerEmail?: string;
};

export default function CheckoutForm({ initialCustomerName, initialCustomerEmail }: CheckoutFormProps) {
  const [state, action, pending] = useActionState(placeOrderAction, undefined);
  // Generated once per mount and reused across every resubmission of this
  // same logical checkout attempt (validation errors, stock errors, a
  // dropped response the user retries by clicking again) — never
  // regenerated by re-renders triggered by useActionState. A genuinely new
  // attempt only happens on a fresh mount of this component (e.g. the user
  // lands on /checkout again after a completed order redirected away), which
  // naturally produces a new key here.
  const [idempotencyKey] = useState(() => crypto.randomUUID());

  return (
    <form action={action} className="flex-1 bg-background rounded-xl border border-border p-6 space-y-4">
      <input type="hidden" name="idempotencyKey" value={idempotencyKey} />

      {state?.formError && (
        <div className="rounded-lg bg-danger/10 border border-danger/30 text-danger px-4 py-3 text-sm">
          {state.formError}
        </div>
      )}

      <div>
        <label htmlFor="customerName" className="block text-sm font-medium text-foreground/80 mb-1">
          Nombre completo
        </label>
        <input
          type="text"
          id="customerName"
          name="customerName"
          defaultValue={initialCustomerName}
          className="w-full"
        />
        {state?.errors?.customerName && (
          <p className="text-sm text-danger mt-1">{state.errors.customerName}</p>
        )}
      </div>

      <div>
        <label htmlFor="customerEmail" className="block text-sm font-medium text-foreground/80 mb-1">
          Correo electrónico
        </label>
        <input
          type="email"
          id="customerEmail"
          name="customerEmail"
          defaultValue={initialCustomerEmail}
          className="w-full"
        />
        {state?.errors?.customerEmail && (
          <p className="text-sm text-danger mt-1">{state.errors.customerEmail}</p>
        )}
      </div>

      <div>
        <label htmlFor="customerPhone" className="block text-sm font-medium text-foreground/80 mb-1">
          Teléfono
        </label>
        <input
          type="text"
          id="customerPhone"
          name="customerPhone"
          className="w-full"
        />
        {state?.errors?.customerPhone && (
          <p className="text-sm text-danger mt-1">{state.errors.customerPhone}</p>
        )}
      </div>

      <div>
        <label htmlFor="address" className="block text-sm font-medium text-foreground/80 mb-1">
          Dirección de entrega
        </label>
        <textarea id="address" name="address" rows={3} className="w-full" />
        {state?.errors?.address && (
          <p className="text-sm text-danger mt-1">{state.errors.address}</p>
        )}
      </div>

      <div>
        <label htmlFor="notes" className="block text-sm font-medium text-foreground/80 mb-1">
          Notas (opcional)
        </label>
        <textarea id="notes" name="notes" rows={2} className="w-full" />
      </div>

      <p className="text-sm text-muted-foreground">
        El pago se coordina directamente con Odentia luego de confirmar el pedido (transferencia o
        contra-entrega).
      </p>

      <button
        type="submit"
        disabled={pending}
        className="w-full bg-primary text-primary-foreground px-6 py-3 rounded-lg font-medium hover:opacity-90 disabled:opacity-60"
      >
        {pending ? "Enviando…" : "Confirmar pedido"}
      </button>
    </form>
  );
}
