"use client";

import { useActionState, useState } from "react";
import { placeOrderAction } from "./actions";

export default function CheckoutForm() {
  const [state, action, pending] = useActionState(placeOrderAction, undefined);
  // Generated once per mount and reused across every resubmission of this
  // same logical checkout attempt (validation errors, stock errors, a
  // dropped response the user retries by clicking again) — never
  // regenerated by re-renders triggered by useActionState. A genuinely new
  // attempt only happens on a fresh mount of this component (e.g. the user
  // lands on /checkout again after a completed order redirected away), which
  // naturally produces a new key here.
  const [idempotencyKey] = useState(() => crypto.randomUUID());

  return (
    <form action={action} className="flex-1 bg-white rounded-xl border border-slate-200 p-6 space-y-4">
      <input type="hidden" name="idempotencyKey" value={idempotencyKey} />

      {state?.formError && (
        <div className="rounded-md bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">
          {state.formError}
        </div>
      )}

      <div>
        <label htmlFor="customerName" className="block text-sm font-medium text-slate-700 mb-1">
          Nombre completo
        </label>
        <input
          type="text"
          id="customerName"
          name="customerName"
          className="w-full rounded-md border-slate-300"
        />
        {state?.errors?.customerName && (
          <p className="text-sm text-red-600 mt-1">{state.errors.customerName}</p>
        )}
      </div>

      <div>
        <label htmlFor="customerEmail" className="block text-sm font-medium text-slate-700 mb-1">
          Correo electrónico
        </label>
        <input
          type="email"
          id="customerEmail"
          name="customerEmail"
          className="w-full rounded-md border-slate-300"
        />
        {state?.errors?.customerEmail && (
          <p className="text-sm text-red-600 mt-1">{state.errors.customerEmail}</p>
        )}
      </div>

      <div>
        <label htmlFor="customerPhone" className="block text-sm font-medium text-slate-700 mb-1">
          Teléfono
        </label>
        <input
          type="text"
          id="customerPhone"
          name="customerPhone"
          className="w-full rounded-md border-slate-300"
        />
        {state?.errors?.customerPhone && (
          <p className="text-sm text-red-600 mt-1">{state.errors.customerPhone}</p>
        )}
      </div>

      <div>
        <label htmlFor="address" className="block text-sm font-medium text-slate-700 mb-1">
          Dirección de entrega
        </label>
        <textarea id="address" name="address" rows={3} className="w-full rounded-md border-slate-300" />
        {state?.errors?.address && (
          <p className="text-sm text-red-600 mt-1">{state.errors.address}</p>
        )}
      </div>

      <div>
        <label htmlFor="notes" className="block text-sm font-medium text-slate-700 mb-1">
          Notas (opcional)
        </label>
        <textarea id="notes" name="notes" rows={2} className="w-full rounded-md border-slate-300" />
      </div>

      <p className="text-sm text-slate-400">
        El pago se coordina directamente con Odentia luego de confirmar el pedido (transferencia o
        contra-entrega).
      </p>

      <button
        type="submit"
        disabled={pending}
        className="w-full bg-teal-700 text-white px-6 py-3 rounded-md font-medium hover:bg-teal-800 disabled:opacity-60"
      >
        {pending ? "Enviando…" : "Confirmar pedido"}
      </button>
    </form>
  );
}
